version: '3.8'

services:
  # PHP 서버 설정
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    networks:
      - webnet

  # MariaDB 데이터베이스 설정
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firstDB
      MYSQL_USER: kang
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db:
  web:
